version: '3'
services:
    database:
        container_name: database
        build:
            context: .
            dockerfile: dockerfileData
        ports:
            - "3307:3306"
        security_opt:
            - no-new-privileges:true
        networks:
            node:
                ipv4_address: 172.20.0.3
        hostname: database
    
    api:
        container_name: api
        build: 
            context: .
            dockerfile: dockerfileNode
        ports:
            - "3000:3000"
        security_opt:
            - no-new-privileges:true
        volumes:
            - ./:/usr/src/app
        networks:
            node:
                ipv4_address: 172.20.0.2
        hostname: api

networks:
    node:
        name: node
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/24